version: '3.8'

services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: zeroback-frontend
    ports:
      - "80:80"
      - "443:443"  # HTTPS -> 일단 필요하진 않음
    volumes:
      # 개발 실시간 업데이트 볼륨
      - ./frontend/client/build:/usr/share/nginx/html:ro
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
      # 로그 볼륨
      - nginx-logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - zeroback-network
    restart: unless-stopped
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend 서비스
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zeroback-backend
    ports:
      - "5000:5000"
    volumes:
      # 개발 시 코드 변경사항 반영
      - ./backend:/app:ro
      - backend-logs:/app/logs
    networks:
      - zeroback-network
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# 네트워크 설정
networks:
  zeroback-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 볼륨 설정
volumes:
  nginx-logs:
    driver: local
  backend-logs:
    driver: local